;
INSERT INTO Airport (ID, NAME, CITY) VALUES (NEXT VALUE FOR AIRPORT_ID_SEQ,'Istanbul Airport', 'Istanbul');
INSERT INTO Airport (ID, NAME, CITY) VALUES (NEXT VALUE FOR AIRPORT_ID_SEQ,'Istanbul Sabiha Gokcen Airport', 'Istanbul');
INSERT INTO Airport (ID, NAME, CITY) VALUES (NEXT VALUE FOR AIRPORT_ID_SEQ,'Charles de Gaulle Airport', 'Paris');
INSERT INTO Airport (ID, NAME, CITY) VALUES (NEXT VALUE FOR AIRPORT_ID_SEQ,'Heathrow Airport','London');
INSERT INTO Airport (ID, NAME, CITY) VALUES (NEXT VALUE FOR AIRPORT_ID_SEQ,'Athens International Airport', 'Athens');
INSERT INTO Airport (ID, NAME, CITY) VALUES (NEXT VALUE FOR AIRPORT_ID_SEQ,'New york International Airport', 'New york');
INSERT INTO Airport (ID, NAME, CITY) VALUES (NEXT VALUE FOR AIRPORT_ID_SEQ,'Hamad International Airport', 'Doha');
INSERT INTO Airport (ID, NAME, CITY) VALUES (NEXT VALUE FOR AIRPORT_ID_SEQ,'Melbourne Airport', 'Melbourne');
INSERT INTO Airport (ID, NAME, CITY) VALUES (NEXT VALUE FOR AIRPORT_ID_SEQ,'Berlin Brandenburg Airport', 'Berlin');
INSERT INTO Airport (ID, NAME, CITY) VALUES (NEXT VALUE FOR AIRPORT_ID_SEQ,'Rio de Janeiro Airport', 'Rio de Janeiro');